// Generated by GitHub Copilot

// Express is the web framework that lets us define API routes and handle HTTP requests.
const express = require('express');

// cors (Cross-Origin Resource Sharing) allows the Angular frontend (running on a
// different port, e.g. localhost:4200) to make requests to this server (localhost:3000).
// Without this, browsers would block those requests as a security measure.
const cors = require('cors');

// These are the three functions we created in db.js to interact with MongoDB.
// We import them here so the routes below can read and write data.
const { getNames, addName, closeConnection } = require('./db');

// Create the Express app — this is the object we attach all routes and middleware to.
const app = express();

// The port this server will listen on. 3000 is a common convention for local development.
const PORT = 3000;

// Middleware: runs on every incoming request before it reaches a route handler.
// cors() adds the headers that allow the frontend to talk to this backend.
app.use(cors());

// express.json() parses incoming request bodies that are JSON (e.g. from POST requests),
// and makes the parsed data available as req.body in route handlers.
app.use(express.json());

// Holds the list of active Server-Sent Event connections (one per open browser tab).
// When data changes, we loop through this array and push updates to each connected client.
let sseClients = [];

// --- ROUTES ---
// A route is a combination of an HTTP method (GET, POST, etc.) and a URL path.
// When a request matches, Express calls the function you provide.

// Health check endpoint — useful for quickly verifying the server is running.
// e.g. visit http://localhost:3000/api/ping in your browser.
app.get('/api/ping', (_req, res) => {
  res.json({ message: 'Successfully hit endpoint' });
});

// GET /api/names — returns the current list of names from MongoDB as a JSON array.
// The Angular frontend calls this when it first loads to populate the list.
app.get('/api/names', async (_req, res) => {
  try {
    const names = await getNames(); // fetch from MongoDB via db.js
    res.json(names);                // send the array back to the caller
  } catch (err) {
    console.error('Error fetching names:', err);
    // 500 means "Internal Server Error" — something went wrong on our end.
    res.status(500).json({ error: 'Failed to fetch names' });
  }
});

// GET /api/names/events — opens a persistent Server-Sent Events (SSE) connection.
// SSE is a one-way channel: the server can push data to the browser at any time
// without the browser needing to poll (repeatedly ask) for updates.
// Each browser tab that loads the app connects here and stays connected.
app.get('/api/names/events', (req, res) => {
  // These headers tell the browser to keep the connection open and expect a stream.
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders(); // send headers immediately to open the stream

  // Register this browser tab as an active SSE client.
  sseClients.push(res);

  // When the browser tab is closed or navigates away, remove it from the list
  // so we don't try to push updates to a dead connection.
  req.on('close', () => {
    sseClients = sseClients.filter(c => c !== res);
  });
});

// POST /api/names — adds a new name to MongoDB.
// The Angular frontend sends a JSON body like { "name": "Alice" } to this endpoint.
app.post('/api/names', async (req, res) => {
  const { name } = req.body; // pull the "name" field out of the request body

  // Validate the input before touching the database.
  // This prevents empty strings or non-string values being saved.
  if (typeof name !== 'string' || !name.trim()) {
    return res.status(400).json({ error: 'name must be a non-empty string' });
    // 400 means "Bad Request" — the caller sent invalid data.
  }

  try {
    const names = await addName(name.trim()); // save to MongoDB, get back updated list

    // After saving, push the updated names list to every connected browser tab via SSE.
    // This is what makes the list update live without a page refresh.
    sseClients.forEach(client => {
      client.write(`data: ${JSON.stringify(names)}\n\n`);
      // SSE messages must follow this exact format: "data: <payload>\n\n"
    });

    return res.json(names); // also return the updated list to the caller
  } catch (err) {
    console.error('Error adding name:', err);
    return res.status(500).json({ error: 'Failed to add name' });
  }
});

// Start the server — it begins listening for incoming HTTP requests on the given port.
app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});

// When you press Ctrl+C to stop the server, Node emits a SIGINT signal.
// We listen for it here to cleanly close the MongoDB connection before exiting,
// rather than just abruptly killing the process.
process.on('SIGINT', async () => {
  await closeConnection();
  process.exit(0);
});
